#Swiftlint configuration file --  https://github.com/realm/SwiftLint
#swiftlint has a bunc of rules you can whitelist or blacklist.
#most of the rules are enabled by default, but some have to be opted in
opt_in_rules:
- force_unwrapping
- weak_delegate
- implicitly_unwrapped_optional
- unowned_variable_capture
- unused_declaration
- closure_end_indentation
- closure_spacing
- contains_over_filter_count
- contains_over_filter_is_empty
- contains_over_first_not_nil
- contains_over_range_nil_comparison
- discouraged_object_literal
- empty_collection_literal
- empty_count
- empty_string
- first_where
- flatmap_over_map_reduce
- function_default_parameter_at_end
- identical_operands
- last_where
- let_var_whitespace
- lower_acl_than_parent
- prefer_zero_over_explicit_init
- sorted_first_last
- sorted_imports
- unused_import

#Some rules have been disabled for now
#To see the list of available rules, you can run swiftlint rules on terminal
#Make sure swiftlint is installed - 'brew install swiftlint'
disabled_rules:
- statement_position
- cyclomatic_complexity
- deployment_target
- discarded_notification_center_observer
- function_body_length
- function_parameter_count
- legacy_cggeometry_functions
- private_unit_test
- type_name
- shorthand_operator
- line_length
- identifier_name
- large_tuple
- type_body_length
- file_length
- multiple_closures_with_trailing_closure
